Importacion de las librerias

In [2]:
import numpy as np
from scipy.signal import convolve2d

Convolucion en 1D

In [3]:
#x = np.array([2, 1, 0, 1, 2])
#h = np.array([1, -1])

x = np.array([1, 1, 1, 1, 1])
h = x

y = np.convolve(x, h, mode='valid')

print("Señal de salida despues de la convolución mode valid: ")
print(y)

z = np.convolve(x, h)

print("Señal de salida despues de la convolución sin mode: ")
print(z)


Señal de salida despues de la convolución mode valid: 
[5]
Señal de salida despues de la convolución sin mode: 
[1 2 3 4 5 4 3 2 1]


Convolucion en 2D discreto

In [ ]:
input_matrix = np.array([[1, 2, 3, 3],
                         [4, 5, 6, 6],
                         [7, 8, 9, 9],
                         [7, 8, 9, 9]])
kernel = np.array([[0, 1, 0],
                   [-1, 1, -1],
                   [0, 1, 0]])

output_matrix = convolve2d(input_matrix, kernel, mode ='valid')

print("Matriz de salida después de la convolucion mode valid: ")
print(output_matrix)

output_matrix2 = convolve2d(input_matrix, kernel)

print("------------------------------------------------------")
print("Matriz de salida después de la convolucion sin mode: ")
print(output_matrix2)


Matriz de salida después de la convolucion mode valid: 
[[5 7]
 [5 7]]
------------------------------------------------------
Matriz de salida después de la convolucion sin mode: 
[[ 0  1  2  3  3  0]
 [-1  3  3  4  6 -3]
 [-4  7  5  7 12 -6]
 [-7 10  5  7 15 -9]
 [-7  6  0  1  9 -9]
 [ 0  7  8  9  9  0]]
